services:
  db:
    ports:
      - ${DB_PORT}:5432
    env_file: .env
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  api:
    build: ./API
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./API:/app
    ports:
      - ${BACKEND_PORT}:8000
    depends_on:
      - db
    environment:
      # Base de donn√©es
      - DATABASE_URL=${DB_URL}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}

      # Django
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  front:
    build: ./Front/autodf
    ports:
      - ${FRONTEND_PORT}:3000
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - front

volumes:
  postgres_data:
